### ISSUE TITLE
UI stuck at loading

### ISSUE THREAD

**Issue by ursuad** [helm/monocular#234]
Hi. I'm trying to deploy Monocular inside our own k8s cluster with a private helm repository. Our service names are routable from the browser, so we don't need (use) the ingress resource. 

The Monocular UI stays stuck at loading ( when I try to access the k8s service created for the UI), even if I don't see any errors in the logs of any of the components. 

The only errors I see are in the Chrome Console (attached)

I will try to provide as much details as I can. Let me know if more information is needed:

![screen shot 2017-04-13 at 4 41 50 pm](https://cloud.githubusercontent.com/assets/12341204/25012380/3c285ed0-2068-11e7-8891-6d1bc9551027.png)

monocular helm chart deployment values.yaml:
```
# Default values for monocular.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
api:
  replicaCount: 1
  image:
    repository: gcr.io/helm-ui/monocular-api
    tag: 25
    pullPolicy: Always
  service:
    name: monocular-api
    type: NodePort
    externalPort: 80
    internalPort: 8081
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  config:
    repos:
      # Official repositories
#      - name: stable
#        url: http://storage.googleapis.com/kubernetes-charts
#        source: https://github.com/kubernetes/charts/tree/master/stable
#      - name: incubator
#        url: http://storage.googleapis.com/kubernetes-charts-incubator
#        source: https://github.com/kubernetes/charts/tree/master/incubator
      # Our Private Helm Repositories
      - name: stable
        url: http://our-private-helm-repo.com:8080/stable
        source: https://github.com/our-private-helm-repo-git-stable
      - name: incubator
        url: http://our-private-helm-repo.com:8080/incubator
        source: https://github.com/our-private-helm-repo-git-incubator
    releasesEnabled: false

ui:
  replicaCount: 1
  image:
    repository: gcr.io/helm-ui/monocular-ui
    tag: 25
    pullPolicy: Always
  service:
    name: monocular-ui
    type: NodePort
    externalPort: 80
    internalPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  # ui-config populate
  googleAnalyticsId: UA-XXXXXX-X
  appName: Monocular

prerender:
  replicaCount: 1
  image:
    repository: migmartri/prerender
    tag: 0.1
    pullPolicy: IfNotPresent
  cacheEnabled: true
  service:
    name: prerender
    type: NodePort
    externalPort: 80
    internalPort: 3000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

ingress:
  hosts:
  # Wildcard
  -
  # - monocular.local

  ## Ingress annotations
  ##
  annotations:
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: 'true'

  ## Ingress TLS configuration
  ## Secrets must be manually created in the namespace
  ##
  # tls:
  #   secretName: monocular.local-tls
```

**monocular-ui logs**
```
Welcome to the Bitnami nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing nginx
nami    INFO  nginx successfully initialized
INFO  ==> Starting nginx...

10.75.153.1 - - [13/Apr/2017:15:12:20 +0000] "GET / HTTP/1.1" 200 2088 "-" "Go-http-client/1.1"
10.75.153.1 - - [13/Apr/2017:15:12:30 +0000] "GET / HTTP/1.1" 200 2088 "-" "Go-http-client/1.1"
10.75.153.1 - - [13/Apr/2017:15:12:30 +0000] "GET / HTTP/1.1" 200 2088 "-" "Go-http-client/1.1"
10.75.196.0 - - [13/Apr/2017:15:12:32 +0000] "GET / HTTP/1.1" 200 2088 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:32 +0000] "GET /assets/css/github-markdown.css HTTP/1.1" 200 4412 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:32 +0000] "GET /styles.f27843cc3a4e0455a3df.bundle.css HTTP/1.1" 200 3819 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:32 +0000] "GET /assets/js/overrides.js HTTP/1.1" 200 132 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:33 +0000] "GET /inline.315c9b139992ffc48900.bundle.js HTTP/1.1" 200 1448 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:33 +0000] "GET /main.4eea1bd7d08955f8839d.bundle.js HTTP/1.1" 200 119863 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:33 +0000] "GET /vendor.27c929509d2b56569f6e.bundle.js HTTP/1.1" 200 261333 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:34 +0000] "GET /api/v1/charts HTTP/1.1" 200 2088 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:34 +0000] "GET /assets/icons/menu.svg HTTP/1.1" 200 215 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:34 +0000] "GET /assets/images/hearth.svg HTTP/1.1" 200 634 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:34 +0000] "GET /assets/images/favicon-16x16.png HTTP/1.1" 200 683 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:34 +0000] "GET /assets/images/favicon-32x32.png HTTP/1.1" 200 1702 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.153.1 - - [13/Apr/2017:15:12:40 +0000] "GET / HTTP/1.1" 200 2088 "-" "Go-http-client/1.1"
10.75.153.1 - - [13/Apr/2017:15:12:40 +0000] "GET / HTTP/1.1" 200 2088 "-" "Go-http-client/1.1"
10.75.196.0 - - [13/Apr/2017:15:12:41 +0000] "GET /inline.315c9b139992ffc48900.bundle.map HTTP/1.1" 200 13548 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:41 +0000] "GET /styles.f27843cc3a4e0455a3df.bundle.map HTTP/1.1" 200 115 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:45 +0000] "GET /main.4eea1bd7d08955f8839d.bundle.map HTTP/1.1" 200 4225945 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:12:49 +0000] "GET /vendor.27c929509d2b56569f6e.bundle.map HTTP/1.1" 200 8943301 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.153.1 - - [13/Apr/2017:15:12:50 +0000] "GET / HTTP/1.1" 200 2088 "-" "Go-http-client/1.1"
10.75.153.1 - - [13/Apr/2017:15:12:50 +0000] "GET / HTTP/1.1" 200 2088 "-" "Go-http-client/1.1"
10.75.196.0 - - [13/Apr/2017:15:15:58 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:15:58 +0000] "GET /assets/js/overrides.js HTTP/1.1" 304 0 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
10.75.196.0 - - [13/Apr/2017:15:15:59 +0000] "GET /assets/images/favicon-16x16.png HTTP/1.1" 200 683 "http://pilfering-bird-monocular-ui.dsp.svc.np.k8s.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
```
**monocular-prerender logs**
```
nami    INFO  Initializing node
nami    INFO  node successfully initialized

  *** Welcome to the node image ***
  *** Brought to you by Bitnami ***
  *** More information: https://github.com/bitnami/bitnami-docker-node ***
  *** Issues: https://github.com/bitnami/bitnami-docker-node/issues ***

2017-04-13T15:11:24.811Z starting worker thread #0
2017-04-13T15:11:24.826Z starting worker thread #1
2017-04-13T15:11:24.842Z starting worker thread #2
2017-04-13T15:11:24.854Z starting worker thread #3
2017-04-13T15:11:24.864Z starting worker thread #4
2017-04-13T15:11:24.877Z starting worker thread #5
2017-04-13T15:11:24.898Z starting worker thread #6
2017-04-13T15:11:24.932Z starting worker thread #7
2017-04-13T15:11:25.154Z starting phantom...
2017-04-13T15:11:25.180Z starting phantom...
2017-04-13T15:11:25.190Z Server running on port 3000

*** New version available: run docker pull bitnami/node:7.8.0-r0 to update. ***

2017-04-13T15:11:25.201Z Server running on port 3000
2017-04-13T15:11:25.203Z starting phantom...
2017-04-13T15:11:25.225Z Server running on port 3000
2017-04-13T15:11:25.304Z starting phantom...
2017-04-13T15:11:25.317Z Server running on port 3000
2017-04-13T15:11:25.333Z starting phantom...
2017-04-13T15:11:25.352Z starting phantom...
2017-04-13T15:11:25.352Z Server running on port 3000
2017-04-13T15:11:25.362Z Server running on port 3000
2017-04-13T15:11:25.399Z starting phantom...
2017-04-13T15:11:25.409Z Server running on port 3000
2017-04-13T15:11:25.434Z starting phantom...
2017-04-13T15:11:25.444Z Server running on port 3000
2017-04-13T15:11:25.891Z started phantom
2017-04-13T15:11:26.034Z started phantom
2017-04-13T15:11:26.050Z started phantom
```

**monocular-api logs**

```
time="2017-04-13T15:11:26Z" level=info msg="Configuration bootstrap init" configFile="/root/monocular/config/monocular.yaml"
time="2017-04-13T15:11:26Z" level=info msg="Configuration file found!"
time="2017-04-13T15:11:26Z" level=info msg="Loading repositories from config file"
time="2017-04-13T15:11:26Z" level=info msg="Configuration bootstrap finished"
time="2017-04-13T15:11:26Z" level=info msg="Using cache directory" path="/root/monocular/repo-data"
time="2017-04-13T15:11:26Z" level=info msg="Local cache missing" name=monocular version=0.1.1
time="2017-04-13T15:11:26Z" level=info msg="Downloading metadata" dest="/root/monocular/repo-data/stable/monocular/0.1.1/chart.tgz" source="http://our-private-helm-repo.com:8080/stable/monocular-0.1.1.tgz"
time="2017-04-13T15:11:26Z" level=info msg="Storing in cache" path="/root/monocular/repo-data/dp-stable/monocular/0.1.1/README.md"
time="2017-04-13T15:11:26Z" level=info msg="Local cache missing" name=our-chart version=0.1.0
time="2017-04-13T15:11:26Z" level=info msg="Downloading metadata" dest="/root/monocular/repo-data/dp-incubator/our-chart/0.1.0/chart.tgz" source="http://our-private-helm-repo.com:8080/incubator/our-chart-0.1.0.tgz"
time="2017-04-13T15:11:26Z" level=info msg="Storing in cache" path="/root/monocular/repo-data/dp-incubator/our-chart/0.1.0/README.md"
2017/04/13 15:11:26 Serving monocular at http://[::]:8081
```
