### ISSUE TITLE
add repository trouble

### ISSUE THREAD

**Issue by obeyler** [helm/monocular#485]
I use the monocular-0.6.3  version deployed with the last helm chart

If I declare the repository inside the value.yml file repositories don't appear into list of repository 
this is my value.yml file
```
     api:
        config:
          cors:
            allowed_origins:
            - https://monocular.mydomain

          repos:
           - name: stable
             url: http://storage.googleapis.com/kubernetes-charts
             source: https://github.com/kubernetes/charts/tree/master/stable
           - name: incubator
             url: https://kubernetes-charts-incubator.storage.googleapis.com
             source: https://github.com/kubernetes/charts/tree/master/incubator
           - name: monocular
             url: https://helm.github.io/monocular
             source: https://github.com/helm/monocular/tree/master/charts

```
and when I try to add new repository whith the ui I've got this error  in top of the dialog box:

> SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 5 of the JSON data

**Comment by prydonius** [comment]
@obeyler do you see any errors in your browsers Javascript console or the Network tab?

**Comment by obeyler** [comment]
The trouble was that monocular-api server couln't be reach
thanks

**Comment by pennpeng** [comment]
same problem，but my monocular-api  can be reach，

**Comment by obeyler** [comment]
@pennpeng  to my part it was due to a wrong indent of my yaml file

```
      api:
        livenessProbe:
          initialDelaySeconds: 1800
        resources:
          limits:
            memory: 526Mi
            cpu: 200m
        config:
          repos:
          - name: stable
            url: http://storage.googleapis.com/kubernetes-charts
            source: https://github.com/kubernetes/charts/tree/master/stable
          - name: incubator
            url: https://kubernetes-charts-incubator.storage.googleapis.com
            source: https://github.com/kubernetes/charts/tree/master/incubator
          - name: monocular
            url: https://helm.github.io/monocular
            source: https://github.com/helm/monocular/tree/master/charts
          - name: internal
            url: https://ingress-ops.((/secrets/cloudfoundry_ops_domain))/chartmuseum

```
to see the difference look at the 'repos:' and the '-name' start on same column
