### ISSUE TITLE
chartmuseum trouble with monocular

### ISSUE THREAD

**Issue by obeyler** [helm/monocular#486]
https://ingress-mydomain.com/chartmuseum/index.yaml 
return a file with this content: 
```
apiVersion: v1
entries:
  istio:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2018-08-02T13:41:54.833344615Z"
    description: Helm chart for all istio components
    digest: c248a3be884cf5763328c6b2661ac989625845567792fd808cacfcdfabf3a40f
    engine: gotpl
    icon: https://istio.io/favicons/android-192x192.png
    keywords:
    - istio
    - security
    - sidecarInjectorWebhook
    - mixer
    - pilot
    - galley
    name: istio
    sources:
    - http://github.com/istio/istio
    tillerVersion: '>=2.7.2-0'
    urls:
    - charts/istio-1.0.0.tgz
    version: 1.0.0
generated: "2018-08-02T13:41:58Z"

```

so as said in issue #395 I add this into repository config 
name: internal
url : https://ingress-mydomain.com/chartmuseum

but it doesn't find any chart and say that the repository is empty
Do you know what is wrong ?
