### ISSUE TITLE
helm install monocular gives no such image: "docker.io/quay.io/helmpack/chartsvc:v1.0.0

### ISSUE THREAD

**Issue by erihanse** [helm/monocular#545]
When executing `helm install monocular/monocular` the chartsvc pods cannot retrieve the docker image. 
I had to fetch the chart, and update in values.yaml:
from:
```
chartsvc: 
  image:
    registry: docker.io
    repository: quay.io/helmpack/chartsvc
```
to:
```
chartsvc:
  image:
    registry: quay.io
    repository: helmpack/chartsvc
    tag: v1.0.0
```
