### ISSUE TITLE
Open monocular blank page

### ISSUE THREAD

**Issue by lou-lan** [helm/monocular#613]
```
helm install --namespace monocular --name monocular monocular/monocular -f custom.yaml
```

custom.yaml
```
ingress:
  hosts:
  - xxx.xxx.xxx
```

<img width="1391" alt="屏幕快照 2019-03-12 10 37 36" src="https://user-images.githubusercontent.com/13095837/54171547-adf82180-44b5-11e9-8fd9-c64578ca8fbb.png">

**Comment by prydonius** [comment]
@lou-lan the console errors you're seeing typically indicates that you're not accessing Monocular correctly. I am guessing you're accessing it through the Ingress given you're setting a host, but could you provide some more info about your setup? What Ingress controller are you using, for example?

**Comment by lou-lan** [comment]
I used nginx-controller, kubeadm, but the `controller.hostNetwork=true` is not set

cat nginx-ingress.yaml
```yaml
controller:
  hostNetwork: true
  replicaCount: 1
  service:
    externalIPs:
      - 172.16.103.2
  nodeSelector:
    node-role.kubernetes.io/edge: ''
  affinity:
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - nginx-ingress
            - key: component
              operator: In
              values:
              - controller
          topologyKey: kubernetes.io/hostname
  tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

defaultBackend:
  nodeSelector:
    node-role.kubernetes.io/edge: ''
  tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

rbac:
  create: true
```

```
helm install stable/nginx-ingress \
-n nginx-ingress \
--namespace nginx-ingress  \
-f nginx-ingress.yaml
```

cat custom.yaml
```yaml
ingress:
  hosts:
  - monocular.xxx.me
ui:
  replicaCount: 1
prerender:
  replicaCount: 1
chartsvc:
  replicas: 1
```

```
helm install --namespace monocular --name monocular monocular/monocular -f custom.yaml
```

dns `monocular.xxx.me` -> `172.16.103.2`
